# yaml-language-server: $schema=https://json.schemastore.org/yamllint.json

apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: demo-template
  title: Demo Template
  description: Software Template used to demo Scaffolder features
spec:
  owner:  backstage/maintainers
  type: website

  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Enter your name
          ui:autofocus: true
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch-patch
      name: Fetch Patch
      action: fetch:template
      input:
        url: ./patch
        values:
          name: ${{parameters.name}}

    - id: publish
      name: Publish
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        title: 'Create new project: ${{parameters.name}}'
        branchName: create-${{parameters.name}}
        description: |
          # New project: ${{parameters.name}}

          ${{ parameters.description if parameters.description }}
        targetPath: ${{ parameters.targetPath if parameters.targetPath else parameters.name }}

  output:
    links:
      - url: ${{steps.publish.output.remoteUrl}}
        title: 'Go to PR'
